"""External dependencies.

Macros defined in this file should be called near the end of the WORKSPACE
file, once the workspace dependencies have been set up.

The go_dependencies() macro is automatically generated by running:
$ bazel run //:gazelle -- update-repos -from_file=go.mod
"""

load("@bazel_gazelle//:deps.bzl", "go_repository")

def go_dependencies():
    """Go dependencies.

    DO NOT EDIT: This macro is auto-generated by running:
    $ bazel run //:gazelle -- update-repos -from_file=go.mod
    """
